------------------------------------------------------------------------------
------------------------------------------------------------------------------
-- Privilege creation script for schemas
-- UTL,VCR,SCHEDULER
--
-- This file was generated from database instance CPAD.
--   Database Time    : 19JAN2005 11:28:39
--   IP address       : 192.5.20.64
--   Database Language: AMERICAN_AMERICA.WE8ISO8859P1
--   Client Machine   : ahl64
--   O/S user         : vcr
-- To run this script from the command line:
-- sqlplus "sys/[password]@[instance] as sysdba" privileges.sql
------------------------------------------------------------------------------

set feedback off

------------------------------------------------------------------------------
prompt Object Privileges
------------------------------------------------------------------------------

prompt Object Privileges granted to VCR:
grant EXECUTE on UTL.GLOBAL to VCR;
grant EXECUTE on UTL.PKG_AUDIT_TRAIL to VCR;
grant EXECUTE on UTL.PKG_AUDIT_TRAIL_MOD to VCR;
grant EXECUTE on UTL.PKG_CONFIG to VCR WITH GRANT OPTION;
grant EXECUTE on UTL.PKG_CONSTANTS to VCR;
grant EXECUTE on UTL.PKG_DATE to VCR;
grant EXECUTE on UTL.PKG_EMAILER to VCR;
grant EXECUTE on UTL.PKG_ERRORHANDLER to VCR;
grant EXECUTE on UTL.PKG_EXCEPTIONS to VCR;
grant EXECUTE on UTL.PKG_HELPDESK to VCR;
grant EXECUTE on UTL.PKG_LOGGER to VCR;
grant EXECUTE on UTL.PKG_MATH to VCR;
grant EXECUTE on UTL.PKG_STRING to VCR;
grant EXECUTE on UTL.PKG_SYSTEM to VCR;
grant EXECUTE on UTL.PKG_TEMP to VCR;
grant EXECUTE on UTL.T_VARCHAR2 to VCR;
grant SELECT on UTL.LOG_MESSAGE to VCR;

prompt System privileges granted to VCR
grant CREATE TABLE to VCR;

prompt Object Privileges granted to UTL:
grant EXECUTE on APP.PKG_SOURCE_LOAD_RUN to UTL;
grant EXECUTE on SYS.DBMS_LOCK to UTL;

prompt Object Privileges granted to APP_ADMIN_ROLE:
grant EXECUTE on APP.PKG_COUNTRY_MOD to APP_ADMIN_ROLE;
grant EXECUTE on APP.PKG_CURRENCY_MOD to APP_ADMIN_ROLE;
grant EXECUTE on APP.PKG_INSTRUMENT_TYPE_MOD to APP_ADMIN_ROLE;
grant EXECUTE on APP.PKG_SOURCE_FUND_MOD to APP_ADMIN_ROLE;
grant EXECUTE on APP.PKG_SOURCE_STRATEGY_MOD to APP_ADMIN_ROLE;
grant EXECUTE on APP.PKG_LIMIT_EXCEPTION_MOD to APP_ADMIN_ROLE;
 
prompt Object Privileges granted to SCHEDULER:
grant EXECUTE on UTL.HOSTCMD to SCHEDULER;
grant EXECUTE on UTL.GLOBAL to SCHEDULER;
grant EXECUTE on UTL.PKG_AUDIT_TRAIL to SCHEDULER;
grant EXECUTE on UTL.PKG_AUDIT_TRAIL_MOD to SCHEDULER;
grant EXECUTE on UTL.PKG_CONFIG to SCHEDULER;
grant EXECUTE on UTL.PKG_CONSTANTS to SCHEDULER;
grant EXECUTE on UTL.PKG_DATE to SCHEDULER;
grant EXECUTE on UTL.PKG_EMAILER to SCHEDULER;
grant EXECUTE on UTL.PKG_ERRORHANDLER to SCHEDULER;
grant EXECUTE on UTL.PKG_EXCEPTIONS to SCHEDULER;
grant EXECUTE on UTL.PKG_HELPDESK to SCHEDULER;
grant EXECUTE on UTL.PKG_LOGGER to SCHEDULER;
grant EXECUTE on UTL.PKG_MATH to SCHEDULER;
grant EXECUTE on UTL.PKG_STRING to SCHEDULER;
grant EXECUTE on UTL.PKG_SYSTEM to SCHEDULER;
grant EXECUTE on UTL.PKG_TEMP to SCHEDULER;
grant EXECUTE on UTL.T_VARCHAR2 to SCHEDULER;
grant SELECT on UTL.CONFIG to SCHEDULER;
grant SELECT on UTL.LOG_MESSAGE to SCHEDULER;
grant SELECT on UTL.AUDIT_TRAIL to SCHEDULER;
grant SELECT on UTL.ERROR_CODES to SCHEDULER;
grant EXECUTE on APP.PKG_DIM_CREATER to SCHEDULER;
grant EXECUTE on APP.PKG_HOUSEKEEPING to SCHEDULER;
grant EXECUTE on APP.PKG_LOADER to SCHEDULER;
grant EXECUTE on APP.PKG_PURGER to SCHEDULER;
grant EXECUTE on APP.PKG_SOURCE to SCHEDULER;
grant EXECUTE on APP.PKG_SOURCE_LOAD_RUN to SCHEDULER;
grant EXECUTE on APP.PKG_VALIDATOR to SCHEDULER;
grant EXECUTE on APP.PKG_REF_OBJECT_MOD to SCHEDULER;
grant EXECUTE on APP.PKG_SOURCE_LOAD_RUN_MOD to SCHEDULER;
grant EXECUTE on APP.PKG_CALCULATOR to SCHEDULER;
grant EXECUTE on APP.PKG_BLOOMBERG to SCHEDULER;
grant EXECUTE on SYS.DBMS_LOCK to SCHEDULER;

prompt System privileges granted to SCHEDULER
grant ANALYZE ANY to SCHEDULER;

prompt Object Privileges granted to APP_IE_ROLE:
grant SELECT on APP.VW_PRM_POSITION_ALL to APP_IE_ROLE;
grant SELECT on APP.VW_PRM_POSITION_LATEST to APP_IE_ROLE;
grant SELECT on APP.VW_SOURCE_LOAD_RUN_STATUS to APP_IE_ROLE;
grant SELECT on APP.VW_SOURCE_LOAD_RUN_FUND_STATUS to APP_IE_ROLE;

prompt Object Privileges granted to PRM:
grant SELECT on APP.VW_PRM_POSITION_ALL to PRM;
grant SELECT on APP.VW_PRM_POSITION_LATEST to PRM;
grant SELECT on APP.VW_SOURCE_LOAD_RUN_STATUS to PRM;
grant SELECT on APP.VW_SOURCE_LOAD_RUN_FUND_STATUS to PRM;

prompt Object Privileges granted to APP_READONLY_ROLE:
grant EXECUTE on APP.PKG_COUNTRY to APP_READONLY_ROLE;
grant EXECUTE on APP.PKG_CURRENCY to APP_READONLY_ROLE;
grant EXECUTE on APP.PKG_INSTRUMENT_TYPE to APP_READONLY_ROLE;
grant EXECUTE on APP.PKG_INVESTMENT_ENGINE to APP_READONLY_ROLE;
grant EXECUTE on APP.PKG_REF_OBJECT to APP_READONLY_ROLE;
grant EXECUTE on APP.PKG_SOURCE to APP_READONLY_ROLE;
grant EXECUTE on APP.PKG_SOURCE_FUND to APP_READONLY_ROLE;
grant EXECUTE on APP.PKG_SOURCE_LOAD_RUN to APP_READONLY_ROLE;
grant EXECUTE on UTL.PKG_USER to APP_READONLY_ROLE;
grant EXECUTE on UTL.PKG_AUDIT_TRAIL to APP_READONLY_ROLE;
grant EXECUTE on APP.PKG_SOURCE_STRATEGY to APP_READONLY_ROLE;
grant EXECUTE on APP.PKG_LIMIT_EXCEPTION to APP_READONLY_ROLE;
grant EXECUTE on APP.PKG_SOURCE_BROKER to APP_READONLY_ROLE;
grant EXECUTE on APP.PKG_SOURCE_POSITION to APP_READONLY_ROLE;
grant EXECUTE on APP.PKG_LIMIT to APP_READONLY_ROLE;

prompt Object Privileges granted to APP_SUPPORT_ROLE:
grant EXECUTE on APP.PKG_SOURCE_LOAD_RUN_MOD to APP_SUPPORT_ROLE;
grant EXECUTE on SCHEDULER.SCHEDULER_MOD to APP_SUPPORT_ROLE;
grant EXECUTE on SCHEDULER.SCHEDULER_GUI to APP_SUPPORT_ROLE;
grant SELECT on UTL.LOG_MESSAGE to APP_SUPPORT_ROLE;
grant execute on utl.pkg_config to vcr_support_role;

prompt Object privileges granted to SCHEDULER_SYS:
GRANT SELECT ON  SYS.V_$PARAMETER TO SCHEDULER_SYS;
GRANT SELECT ON  SYS.V_$PROCESS TO SCHEDULER_SYS;
GRANT SELECT ON  SYS.V_$SESSION TO SCHEDULER_SYS;

prompt Object privileges to OPS$VCR:
GRANT EXECUTE ON SCHEDULER.SCHEDULER_CON TO OPS$VCR;

prompt System privileges granted to APP_GUI
grant CREATE TABLE to APP_GUI;
grant CREATE SEQUENCE to APP_GUI;


prompt Role privileges granted to users/roles
grant APP_READONLY_ROLE to VCR_SUPPORT_ROLE;
grant APP_READONLY_ROLE to VCR_ADMIN_ROLE;
-- prm_vcr for use with potential future database link
grant APP_IE_ROLE to PRM_VCR;
-- prm used when vcr and prm share same instance
grant APP_IE_ROLE to PRM;
GRANT SCHEDULER_SYS to SCHEDULER;

PROMPT Object privileges granted to APP_REPORT_USER

GRANT SELECT ON APP.VW_REP_STD_EXCEPTION TO APP_REPORT_ROLE;
GRANT SELECT ON APP.VW_REP_FUND_ROR_TOL TO APP_REPORT_ROLE;
GRANT SELECT ON APP.VW_REP_PRM_BROKER_CASH TO APP_REPORT_ROLE;
GRANT SELECT ON APP.VW_REP_NUM_TRADES_PER_INSTRMNT TO APP_REPORT_ROLE;
GRANT SELECT ON APP.VW_REP_FILE_AVAILIBILTY_BY_SRC TO APP_REPORT_ROLE;
GRANT SELECT ON APP.VW_REP_FILE_AVAILIBILTY_BY_FND TO APP_REPORT_ROLE;
GRANT SELECT ON APP.VW_REP_DAILY_POSITIONS_LOADED TO APP_REPORT_ROLE;
GRANT SELECT ON APP.VW_REP_DAILY_ATTRIB_CHECK_FAIL TO APP_REPORT_ROLE;
GRANT SELECT ON APP.VW_REP_DAILY_EXCEPTIONS TO APP_REPORT_ROLE;
GRANT SELECT ON APP.VW_REP_POS_DAILY_EXCEPTIONS TO APP_REPORT_ROLE;
GRANT SELECT ON APP.VW_REP_POS_DAILY_XPN_RSVLD_STA TO APP_REPORT_ROLE;
GRANT SELECT ON APP.IE_PLATFORM TO APP_REPORT_ROLE;
GRANT SELECT ON APP.INVESTMENT_ENGINE TO APP_REPORT_ROLE;
GRANT SELECT ON APP.PRIME_BROKER TO APP_REPORT_ROLE;
GRANT SELECT ON APP.SOURCE TO APP_REPORT_ROLE;
GRANT SELECT ON APP.SOURCE_BASIS TO APP_REPORT_ROLE;
GRANT SELECT ON APP.SOURCE_FUND TO APP_REPORT_ROLE;
GRANT SELECT ON APP.SOURCE_INSTRUMENT_TYPE TO APP_REPORT_ROLE;
GRANT SELECT ON APP.SOURCE_STRATEGY TO APP_REPORT_ROLE;
GRANT SELECT ON APP.VW_STD_EXCEPTION_REPORT_PARAM TO APP_REPORT_ROLE;

PROMPT PITA grants

grant select on vw_pita_fund_mtd_pnl to vcr_pita_role;
grant vcr_pita_role to pita_vcr_user;

PROMPT MACRISK grants

grant select on vw_macrisk_position to vcr_macrisk_role;
grant vcr_macrisk_role to macrisk_vcr_user;







exit

------------------------------------------------------------------------------
-- end of file
------------------------------------------------------------------------------

